"""comments

Revision ID: dc1f60725c30
Revises: 9a54d281caca
Create Date: 2024-11-26 16:56:01.931805

"""

import os

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'dc1f60725c30'
down_revision = '9a54d281caca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'ods_timetable_act',
        'name',
        existing_type=sa.VARCHAR(),
        comment='html часть с названием предмета, аудиторией и преподавателем',
        existing_nullable=False,
        schema='ODS_TIMETABLE',
    )
    op.alter_column(
        'ods_timetable_act',
        'odd',
        existing_type=sa.BOOLEAN(),
        comment='пара по четным неделям',
        existing_nullable=False,
        schema='ODS_TIMETABLE',
    )
    op.alter_column(
        'ods_timetable_act',
        'even',
        existing_type=sa.BOOLEAN(),
        comment='пара по нечетным неделям',
        existing_nullable=False,
        schema='ODS_TIMETABLE',
    )
    op.alter_column(
        "ods_timetable_act",
        'weekday',
        existing_type=sa.INTEGER(),
        comment='номер дня недели',
        existing_nullable=False,
        schema='ODS_TIMETABLE',
    )
    op.alter_column(
        'ods_timetable_act',
        'num',
        existing_type=sa.INTEGER(),
        comment='номер пары',
        existing_nullable=False,
        schema='ODS_TIMETABLE',
    )
    op.alter_column(
        'ods_timetable_act',
        'start',
        existing_type=sa.VARCHAR(),
        comment='hh:mm',
        existing_nullable=False,
        schema='ODS_TIMETABLE',
    )
    op.alter_column(
        'ods_timetable_act',
        'end',
        existing_type=sa.VARCHAR(),
        comment='hh:mm',
        existing_nullable=False,
        schema='ODS_TIMETABLE',
    )
    op.alter_column(
        'ods_timetable_act',
        'group',
        existing_type=sa.VARCHAR(),
        comment='название группы',
        existing_nullable=False,
        schema='ODS_TIMETABLE',
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'ods_timetable_act',
        'group',
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment='название группы',
        existing_nullable=False,
        schema='ODS_TIMETABLE',
    )
    op.alter_column(
        'ods_timetable_act',
        'end',
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment='hh:mm',
        existing_nullable=False,
        schema='ODS_TIMETABLE',
    )
    op.alter_column(
        'ods_timetable_act',
        'start',
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment='hh:mm',
        existing_nullable=False,
        schema='ODS_TIMETABLE',
    )
    op.alter_column(
        'ods_timetable_act',
        'num',
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment='номер пары',
        existing_nullable=False,
        schema='ODS_TIMETABLE',
    )
    op.alter_column(
        "ods_timetable_act",
        'weekday',
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment='номер дня недели',
        existing_nullable=False,
        schema='ODS_TIMETABLE',
    )
    op.alter_column(
        'ods_timetable_act',
        'even',
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment='пара по нечетным неделям',
        existing_nullable=False,
        schema='ODS_TIMETABLE',
    )
    op.alter_column(
        'ods_timetable_act',
        'odd',
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment='пара по четным неделям',
        existing_nullable=False,
        schema='ODS_TIMETABLE',
    )
    op.alter_column(
        'ods_timetable_act',
        'name',
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment='html часть с названием предмета, аудиторией и преподавателем',
        existing_nullable=False,
        schema='ODS_TIMETABLE',
    )
    # ### end Alembic commands ###
