"""test

Revision ID: 6749515dcd89
Revises: 5714921e11a0
Create Date: 2024-06-26 14:08:18.998984

"""

from alembic import op
import sqlalchemy as sa
import os


# revision identifiers, used by Alembic.
revision = '6749515dcd89'
down_revision = '5714921e11a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table_schema("STG_TEST")
    op.create_table_schema("ODS_TIMETABLE")
    op.create_table(
        'ods_timetable_act',
        sa.Column('event_text', sa.String(), nullable=True),
        sa.Column('time_interval_text', sa.String(), nullable=True),
        sa.Column('group_text', sa.String(), nullable=True),
        schema='ODS_TIMETABLE',
    )
    op.create_table(
        'test',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        schema='STG_TEST',
    )
    op.create_group("test_dwh_stg_test_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_test_read")
    op.create_group(
        "test_dwh_stg_test_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_test_write"
    )
    op.create_group("test_dwh_stg_test_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_test_all")
    op.create_group(
        "test_dwh_ods_timetable_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_timetable_read"
    )
    op.create_group(
        "test_dwh_ods_timetable_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_timetable_write"
    )
    op.create_group(
        "test_dwh_ods_timetable_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_timetable_all"
    )
    op.grant_on_schema(
        "test_dwh_stg_test_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_test_read", "STG_TEST"
    )
    op.grant_on_schema(
        "test_dwh_stg_test_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_test_write", "STG_TEST"
    )
    op.grant_on_schema(
        "test_dwh_stg_test_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_test_all", "STG_TEST"
    )
    op.grant_on_schema(
        "test_dwh_ods_timetable_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_timetable_read",
        "ODS_TIMETABLE",
    )
    op.grant_on_schema(
        "test_dwh_ods_timetable_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_timetable_write",
        "ODS_TIMETABLE",
    )
    op.grant_on_schema(
        "test_dwh_ods_timetable_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_timetable_all",
        "ODS_TIMETABLE",
    )
    op.grant_on_table(
        "test_dwh_stg_test_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_test_read",
        ['SELECT'],
        '"STG_TEST".test',
    )
    op.grant_on_table(
        "test_dwh_stg_test_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_test_write",
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"STG_TEST".test',
    )
    op.grant_on_table(
        "test_dwh_stg_test_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_test_all",
        ['ALL'],
        '"STG_TEST".test',
    )
    op.grant_on_table(
        "test_dwh_ods_timetable_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_timetable_read",
        ['SELECT'],
        '"ODS_TIMETABLE".ods_timetable_act',
    )
    op.grant_on_table(
        "test_dwh_ods_timetable_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_timetable_write",
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"ODS_TIMETABLE".ods_timetable_act',
    )
    op.grant_on_table(
        "test_dwh_ods_timetable_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_timetable_all",
        ['ALL'],
        '"ODS_TIMETABLE".ods_timetable_act',
    )
    op.create_index(
        op.f('ix_ODS_TIMETABLE_ods_timetable_act_event_text'),
        'ods_timetable_act',
        ['event_text'],
        unique=False,
        schema='ODS_TIMETABLE',
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_ODS_TIMETABLE_ods_timetable_act_event_text'), table_name='ods_timetable_act', schema='ODS_TIMETABLE'
    )
    op.revoke_on_table(
        "test_dwh_ods_timetable_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_timetable_all",
        ['ALL'],
        '"ODS_TIMETABLE".ods_timetable_act',
    )
    op.revoke_on_table(
        "test_dwh_ods_timetable_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_timetable_write",
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"ODS_TIMETABLE".ods_timetable_act',
    )
    op.revoke_on_table(
        "test_dwh_ods_timetable_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_timetable_read",
        ['SELECT'],
        '"ODS_TIMETABLE".ods_timetable_act',
    )
    op.revoke_on_table(
        "test_dwh_stg_test_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_test_all",
        ['ALL'],
        '"STG_TEST".test',
    )
    op.revoke_on_table(
        "test_dwh_stg_test_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_test_write",
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"STG_TEST".test',
    )
    op.revoke_on_table(
        "test_dwh_stg_test_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_test_read",
        ['SELECT'],
        '"STG_TEST".test',
    )
    op.revoke_on_schema(
        "test_dwh_ods_timetable_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_timetable_all",
        "ODS_TIMETABLE",
    )
    op.revoke_on_schema(
        "test_dwh_ods_timetable_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_timetable_write",
        "ODS_TIMETABLE",
    )
    op.revoke_on_schema(
        "test_dwh_ods_timetable_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_timetable_read",
        "ODS_TIMETABLE",
    )
    op.revoke_on_schema(
        "test_dwh_stg_test_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_test_all", "STG_TEST"
    )
    op.revoke_on_schema(
        "test_dwh_stg_test_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_test_write", "STG_TEST"
    )
    op.revoke_on_schema(
        "test_dwh_stg_test_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_test_read", "STG_TEST"
    )
    op.drop_index(
        op.f('ix_ODS_TIMETABLE_ods_timetable_act_event_text'), table_name='ods_timetable_act', schema='ODS_TIMETABLE'
    )
    op.drop_table('test', schema='STG_TEST')
    op.drop_table('ods_timetable_act', schema='ODS_TIMETABLE')
    op.delete_group(
        "test_dwh_ods_timetable_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_timetable_all"
    )
    op.delete_group(
        "test_dwh_ods_timetable_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_timetable_write"
    )
    op.delete_group(
        "test_dwh_ods_timetable_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_timetable_read"
    )
    op.delete_group("test_dwh_stg_test_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_test_all")
    op.delete_group(
        "test_dwh_stg_test_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_test_write"
    )
    op.delete_group("test_dwh_stg_test_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_test_read")
    op.drop_table_schema("ODS_TIMETABLE")
    # ### end Alembic commands ###
