"""dm_logs

Revision ID: b003a52d0992
Revises: 7a18bd9ff633
Create Date: 2024-05-31 23:33:27.403140

"""

import os

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'b003a52d0992'
down_revision = '7a18bd9ff633'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'incident',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'container_name', sa.String(), nullable=False, comment='Имя контейнера, в котором произошла ошибочка'
        ),
        sa.Column('message', sa.String(), nullable=False, comment='Сообщение об ошибке'),
        sa.Column('create_ts', sa.DateTime(), nullable=False, comment='Время, когда произошла ошибка'),
        sa.PrimaryKeyConstraint('id'),
        schema='DM_INFRA_LOGS',
        comment='Информация об ошибках по контейнерам',
    )
    op.grant_on_table(
        "test_dwh_dm_infra_logs_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_dm_infra_logs_read",
        ['SELECT'],
        '"DM_INFRA_LOGS".incident',
    )
    op.grant_on_table(
        "test_dwh_dm_infra_logs_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_dm_infra_logs_write",
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"DM_INFRA_LOGS".incident',
    )
    op.grant_on_table(
        "test_dwh_dm_infra_logs_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_dm_infra_logs_all",
        ['ALL'],
        '"DM_INFRA_LOGS".incident',
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.revoke_on_table(
        "test_dwh_dm_infra_logs_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_dm_infra_logs_all",
        ['ALL'],
        '"DM_INFRA_LOGS".incident',
    )
    op.revoke_on_table(
        "test_dwh_dm_infra_logs_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_dm_infra_logs_write",
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"DM_INFRA_LOGS".incident',
    )
    op.revoke_on_table(
        "test_dwh_dm_infra_logs_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_dm_infra_logs_read",
        ['SELECT'],
        '"DM_INFRA_LOGS".incident',
    )
    op.drop_table('incident', schema='DM_INFRA_LOGS')
    # ### end Alembic commands ###
