"""ods_timetable_act

Revision ID: 0c92e25783aa
Revises: 0d1fae4a86d7
Create Date: 2024-07-29 14:54:38.955496

"""

from alembic import op
import sqlalchemy as sa
import os


# revision identifiers, used by Alembic.
revision = '0c92e25783aa'
down_revision = '0d1fae4a86d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_schema("ODS_TIMETABLE")
    op.create_table_schema("DWH_ODS_TIMETABLE_ACT")
    op.create_table(
        'ods_timetable_act',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('event_text', sa.String(), nullable=False, comment='Мероприятие'),
        sa.Column('time_interval', sa.String(), nullable=False, comment='Время'),
        sa.Column('group_text', sa.String(), nullable=False, comment='Номер группы'),
        sa.PrimaryKeyConstraint('id'),
        schema='DWH_ODS_TIMETABLE_ACT',
    )
    op.create_table(
        'ods_timetable_act',
        sa.Column('event_text', sa.String(), nullable=True),
        sa.Column('time_interval_text', sa.String(), nullable=True),
        sa.Column('group_text', sa.String(), nullable=True),
        schema='ODS_TIMETABLE',
    )
    op.create_group(
        "test_dwh_ods_timetable_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_timetable_read"
    )
    op.create_group(
        "test_dwh_ods_timetable_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_timetable_write"
    )
    op.create_group(
        "test_dwh_ods_timetable_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_timetable_all"
    )
    op.create_group(
        "test_dwh_dwh_ods_timetable_act_read"
        if os.getenv("ENVIRONMENT") != "production"
        else "prod_dwh_dwh_ods_timetable_act_read"
    )
    op.create_group(
        "test_dwh_dwh_ods_timetable_act_write"
        if os.getenv("ENVIRONMENT") != "production"
        else "prod_dwh_dwh_ods_timetable_act_write"
    )
    op.create_group(
        "test_dwh_dwh_ods_timetable_act_all"
        if os.getenv("ENVIRONMENT") != "production"
        else "prod_dwh_dwh_ods_timetable_act_all"
    )
    op.grant_on_schema(
        "test_dwh_ods_timetable_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_timetable_read",
        "ODS_TIMETABLE",
    )
    op.grant_on_schema(
        "test_dwh_ods_timetable_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_timetable_write",
        "ODS_TIMETABLE",
    )
    op.grant_on_schema(
        "test_dwh_ods_timetable_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_timetable_all",
        "ODS_TIMETABLE",
    )
    op.grant_on_schema(
        (
            "test_dwh_dwh_ods_timetable_act_read"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_dwh_dwh_ods_timetable_act_read"
        ),
        "DWH_ODS_TIMETABLE_ACT",
    )
    op.grant_on_schema(
        (
            "test_dwh_dwh_ods_timetable_act_write"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_dwh_dwh_ods_timetable_act_write"
        ),
        "DWH_ODS_TIMETABLE_ACT",
    )
    op.grant_on_schema(
        (
            "test_dwh_dwh_ods_timetable_act_all"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_dwh_dwh_ods_timetable_act_all"
        ),
        "DWH_ODS_TIMETABLE_ACT",
    )
    op.grant_on_table(
        "test_dwh_ods_timetable_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_timetable_read",
        ['SELECT'],
        '"ODS_TIMETABLE".ods_timetable_act',
    )
    op.grant_on_table(
        "test_dwh_ods_timetable_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_timetable_write",
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"ODS_TIMETABLE".ods_timetable_act',
    )
    op.grant_on_table(
        "test_dwh_ods_timetable_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_timetable_all",
        ['ALL'],
        '"ODS_TIMETABLE".ods_timetable_act',
    )
    op.grant_on_table(
        (
            "test_dwh_dwh_ods_timetable_act_read"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_dwh_dwh_ods_timetable_act_read"
        ),
        ['SELECT'],
        '"DWH_ODS_TIMETABLE_ACT".ods_timetable_act',
    )
    op.grant_on_table(
        (
            "test_dwh_dwh_ods_timetable_act_write"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_dwh_dwh_ods_timetable_act_write"
        ),
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"DWH_ODS_TIMETABLE_ACT".ods_timetable_act',
    )
    op.grant_on_table(
        (
            "test_dwh_dwh_ods_timetable_act_all"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_dwh_dwh_ods_timetable_act_all"
        ),
        ['ALL'],
        '"DWH_ODS_TIMETABLE_ACT".ods_timetable_act',
    )
    op.grant_on_table(
        (
            "test_dwh_dwh_ods_timetable_act_read"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_dwh_dwh_ods_timetable_act_read"
        ),
        ['SELECT'],
        '"DWH_ODS_TIMETABLE_ACT".ods_timetable_act',
    )
    op.grant_on_table(
        (
            "test_dwh_dwh_ods_timetable_act_write"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_dwh_dwh_ods_timetable_act_write"
        ),
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"DWH_ODS_TIMETABLE_ACT".ods_timetable_act',
    )
    op.grant_on_table(
        (
            "test_dwh_dwh_ods_timetable_act_all"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_dwh_dwh_ods_timetable_act_all"
        ),
        ['ALL'],
        '"DWH_ODS_TIMETABLE_ACT".ods_timetable_act',
    )
    op.create_index(
        op.f('ix_ODS_TIMETABLE_ods_timetable_act_event_text'),
        'ods_timetable_act',
        ['event_text'],
        unique=False,
        schema='ODS_TIMETABLE',
    )
    op.grant_on_table(
        "test_dwh_ods_timetable_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_timetable_read",
        ['SELECT'],
        '"ODS_TIMETABLE".ods_timetable_act',
    )
    op.grant_on_table(
        "test_dwh_ods_timetable_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_timetable_write",
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"ODS_TIMETABLE".ods_timetable_act',
    )
    op.grant_on_table(
        "test_dwh_ods_timetable_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_timetable_all",
        ['ALL'],
        '"ODS_TIMETABLE".ods_timetable_act',
    )
    op.add_column('dim_room_act', sa.Column('room_api_id', sa.Integer(), nullable=False), schema='DM_TIMETABLE')
    op.add_column('dim_room_act', sa.Column('room_name', sa.String(), nullable=True), schema='DM_TIMETABLE')
    op.add_column('dim_room_act', sa.Column('room_is_deleted', sa.Boolean(), nullable=False), schema='DM_TIMETABLE')
    op.add_column('dim_room_act', sa.Column('room_department', sa.String(), nullable=True), schema='DM_TIMETABLE')
    op.drop_column('dim_room_act', 'department', schema='DM_TIMETABLE')
    op.drop_column('dim_room_act', 'name', schema='DM_TIMETABLE')
    op.drop_column('dim_room_act', 'api_id', schema='DM_TIMETABLE')
    op.drop_column('dim_room_act', 'is_deleted', schema='DM_TIMETABLE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'dim_room_act',
        sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
        schema='DM_TIMETABLE',
    )
    op.add_column(
        'dim_room_act', sa.Column('api_id', sa.INTEGER(), autoincrement=False, nullable=False), schema='DM_TIMETABLE'
    )
    op.add_column(
        'dim_room_act', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True), schema='DM_TIMETABLE'
    )
    op.add_column(
        'dim_room_act', sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=True), schema='DM_TIMETABLE'
    )
    op.drop_column('dim_room_act', 'room_department', schema='DM_TIMETABLE')
    op.drop_column('dim_room_act', 'room_is_deleted', schema='DM_TIMETABLE')
    op.drop_column('dim_room_act', 'room_name', schema='DM_TIMETABLE')
    op.drop_column('dim_room_act', 'room_api_id', schema='DM_TIMETABLE')
    op.revoke_on_table(
        "test_dwh_ods_timetable_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_timetable_all",
        ['ALL'],
        '"ODS_TIMETABLE".ods_timetable_act',
    )
    op.revoke_on_table(
        "test_dwh_ods_timetable_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_timetable_write",
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"ODS_TIMETABLE".ods_timetable_act',
    )
    op.revoke_on_table(
        "test_dwh_ods_timetable_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_timetable_read",
        ['SELECT'],
        '"ODS_TIMETABLE".ods_timetable_act',
    )
    op.drop_index(
        op.f('ix_ODS_TIMETABLE_ods_timetable_act_event_text'), table_name='ods_timetable_act', schema='ODS_TIMETABLE'
    )
    op.revoke_on_table(
        (
            "test_dwh_dwh_ods_timetable_act_all"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_dwh_dwh_ods_timetable_act_all"
        ),
        ['ALL'],
        '"DWH_ODS_TIMETABLE_ACT".ods_timetable_act',
    )
    op.revoke_on_table(
        (
            "test_dwh_dwh_ods_timetable_act_write"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_dwh_dwh_ods_timetable_act_write"
        ),
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"DWH_ODS_TIMETABLE_ACT".ods_timetable_act',
    )
    op.revoke_on_table(
        (
            "test_dwh_dwh_ods_timetable_act_read"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_dwh_dwh_ods_timetable_act_read"
        ),
        ['SELECT'],
        '"DWH_ODS_TIMETABLE_ACT".ods_timetable_act',
    )
    op.revoke_on_table(
        (
            "test_dwh_dwh_ods_timetable_act_all"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_dwh_dwh_ods_timetable_act_all"
        ),
        ['ALL'],
        '"DWH_ODS_TIMETABLE_ACT".ods_timetable_act',
    )
    op.revoke_on_table(
        (
            "test_dwh_dwh_ods_timetable_act_write"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_dwh_dwh_ods_timetable_act_write"
        ),
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"DWH_ODS_TIMETABLE_ACT".ods_timetable_act',
    )
    op.revoke_on_table(
        (
            "test_dwh_dwh_ods_timetable_act_read"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_dwh_dwh_ods_timetable_act_read"
        ),
        ['SELECT'],
        '"DWH_ODS_TIMETABLE_ACT".ods_timetable_act',
    )
    op.revoke_on_table(
        "test_dwh_ods_timetable_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_timetable_all",
        ['ALL'],
        '"ODS_TIMETABLE".ods_timetable_act',
    )
    op.revoke_on_table(
        "test_dwh_ods_timetable_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_timetable_write",
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"ODS_TIMETABLE".ods_timetable_act',
    )
    op.revoke_on_table(
        "test_dwh_ods_timetable_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_timetable_read",
        ['SELECT'],
        '"ODS_TIMETABLE".ods_timetable_act',
    )
    op.revoke_on_schema(
        (
            "test_dwh_dwh_ods_timetable_act_all"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_dwh_dwh_ods_timetable_act_all"
        ),
        "DWH_ODS_TIMETABLE_ACT",
    )
    op.revoke_on_schema(
        (
            "test_dwh_dwh_ods_timetable_act_write"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_dwh_dwh_ods_timetable_act_write"
        ),
        "DWH_ODS_TIMETABLE_ACT",
    )
    op.revoke_on_schema(
        (
            "test_dwh_dwh_ods_timetable_act_read"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_dwh_dwh_ods_timetable_act_read"
        ),
        "DWH_ODS_TIMETABLE_ACT",
    )
    op.revoke_on_schema(
        "test_dwh_ods_timetable_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_timetable_all",
        "ODS_TIMETABLE",
    )
    op.revoke_on_schema(
        "test_dwh_ods_timetable_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_timetable_write",
        "ODS_TIMETABLE",
    )
    op.revoke_on_schema(
        "test_dwh_ods_timetable_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_timetable_read",
        "ODS_TIMETABLE",
    )
    op.drop_table('ods_timetable_act', schema='ODS_TIMETABLE')
    op.drop_table('ods_timetable_act', schema='DWH_ODS_TIMETABLE_ACT')
    op.delete_group(
        "test_dwh_dwh_ods_timetable_act_all"
        if os.getenv("ENVIRONMENT") != "production"
        else "prod_dwh_dwh_ods_timetable_act_all"
    )
    op.delete_group(
        "test_dwh_dwh_ods_timetable_act_write"
        if os.getenv("ENVIRONMENT") != "production"
        else "prod_dwh_dwh_ods_timetable_act_write"
    )
    op.delete_group(
        "test_dwh_dwh_ods_timetable_act_read"
        if os.getenv("ENVIRONMENT") != "production"
        else "prod_dwh_dwh_ods_timetable_act_read"
    )
    op.delete_group(
        "test_dwh_ods_timetable_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_timetable_all"
    )
    op.delete_group(
        "test_dwh_ods_timetable_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_timetable_write"
    )
    op.delete_group(
        "test_dwh_ods_timetable_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_timetable_read"
    )
    op.drop_table_schema("DWH_ODS_TIMETABLE_ACT")
    op.drop_table_schema("ODS_TIMETABLE")
    # ### end Alembic commands ###
