"""add dim_cabnet_act to DM

Revision ID: 94699f7481fb
Revises: d459997cd681
Create Date: 2024-05-10 12:12:34.202208

"""

from alembic import op
import sqlalchemy as sa
import os

# revision identifiers, used by Alembic.
revision = '94699f7481fb'
down_revision = 'd459997cd681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table_schema("STG_RASPHYSMSU")
    op.create_table_schema("DM_DIM_CABNET_ACT")
    op.create_table(
        'dim_cabnet_act',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('cabinet_direction_text_type', sa.String(), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.Column('department', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        schema='DM_DIM_CABNET_ACT',
    )
    op.create_group(
        "test_dwh_dm_dim_cabnet_act_read"
        if os.getenv("ENVIRONMENT") != "production"
        else "prod_dwh_dm_dim_cabnet_act_read"
    )
    op.create_group(
        "test_dwh_dm_dim_cabnet_act_write"
        if os.getenv("ENVIRONMENT") != "production"
        else "prod_dwh_dm_dim_cabnet_act_write"
    )
    op.create_group(
        "test_dwh_dm_dim_cabnet_act_all"
        if os.getenv("ENVIRONMENT") != "production"
        else "prod_dwh_dm_dim_cabnet_act_all"
    )
    op.grant_on_schema(
        (
            "test_dwh_dm_dim_cabnet_act_read"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_dwh_dm_dim_cabnet_act_read"
        ),
        "DM_DIM_CABNET_ACT",
    )
    op.grant_on_schema(
        (
            "test_dwh_dm_dim_cabnet_act_write"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_dwh_dm_dim_cabnet_act_write"
        ),
        "DM_DIM_CABNET_ACT",
    )
    op.grant_on_schema(
        (
            "test_dwh_dm_dim_cabnet_act_all"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_dwh_dm_dim_cabnet_act_all"
        ),
        "DM_DIM_CABNET_ACT",
    )
    op.grant_on_table(
        (
            "test_dwh_dm_dim_cabnet_act_read"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_dwh_dm_dim_cabnet_act_read"
        ),
        ['SELECT'],
        '"DM_DIM_CABNET_ACT".dim_cabnet_act',
    )
    op.grant_on_table(
        (
            "test_dwh_dm_dim_cabnet_act_write"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_dwh_dm_dim_cabnet_act_write"
        ),
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"DM_DIM_CABNET_ACT".dim_cabnet_act',
    )
    op.grant_on_table(
        (
            "test_dwh_dm_dim_cabnet_act_all"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_dwh_dm_dim_cabnet_act_all"
        ),
        ['ALL'],
        '"DM_DIM_CABNET_ACT".dim_cabnet_act',
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.revoke_on_table(
        (
            "test_dwh_dm_dim_cabnet_act_all"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_dwh_dm_dim_cabnet_act_all"
        ),
        ['ALL'],
        '"DM_DIM_CABNET_ACT".dim_cabnet_act',
    )
    op.revoke_on_table(
        (
            "test_dwh_dm_dim_cabnet_act_write"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_dwh_dm_dim_cabnet_act_write"
        ),
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"DM_DIM_CABNET_ACT".dim_cabnet_act',
    )
    op.revoke_on_table(
        (
            "test_dwh_dm_dim_cabnet_act_read"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_dwh_dm_dim_cabnet_act_read"
        ),
        ['SELECT'],
        '"DM_DIM_CABNET_ACT".dim_cabnet_act',
    )
    op.revoke_on_schema(
        (
            "test_dwh_dm_dim_cabnet_act_all"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_dwh_dm_dim_cabnet_act_all"
        ),
        "DM_DIM_CABNET_ACT",
    )
    op.revoke_on_schema(
        (
            "test_dwh_dm_dim_cabnet_act_write"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_dwh_dm_dim_cabnet_act_write"
        ),
        "DM_DIM_CABNET_ACT",
    )
    op.revoke_on_schema(
        (
            "test_dwh_dm_dim_cabnet_act_read"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_dwh_dm_dim_cabnet_act_read"
        ),
        "DM_DIM_CABNET_ACT",
    )
    op.drop_table('dim_cabnet_act', schema='DM_DIM_CABNET_ACT')
    op.delete_group(
        "test_dwh_dm_dim_cabnet_act_all"
        if os.getenv("ENVIRONMENT") != "production"
        else "prod_dwh_dm_dim_cabnet_act_all"
    )
    op.delete_group(
        "test_dwh_dm_dim_cabnet_act_write"
        if os.getenv("ENVIRONMENT") != "production"
        else "prod_dwh_dm_dim_cabnet_act_write"
    )
    op.delete_group(
        "test_dwh_dm_dim_cabnet_act_read"
        if os.getenv("ENVIRONMENT") != "production"
        else "prod_dwh_dm_dim_cabnet_act_read"
    )
    op.drop_table_schema("DM_DIM_CABNET_ACT")
    # op.drop_table_schema("STG_RASPHYSMSU")
    # ### end Alembic commands ###
