"""fix-rental

Revision ID: cbbfd63d5260
Revises: 83a86d9e5c9b
Create Date: 2025-05-09 02:53:53.444154

"""

import os

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'cbbfd63d5260'
down_revision = '83a86d9e5c9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
