"""Apply new definitions-lib changes

Revision ID: af84d0ad7c58
Revises: ab55e423b1e4
Create Date: 2025-11-15 00:12:36.907971

"""

import os

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'af84d0ad7c58'
down_revision = 'ab55e423b1e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_group(
        "test_sensitive_dwh_stg_userdata_all"
        if os.getenv("ENVIRONMENT") != "production"
        else "prod_sensitive_dwh_stg_userdata_all"
    )
    op.create_group(
        "test_sensitive_dwh_stg_userdata_write"
        if os.getenv("ENVIRONMENT") != "production"
        else "prod_sensitive_dwh_stg_userdata_write"
    )
    op.create_group(
        "test_sensitive_dwh_stg_userdata_read"
        if os.getenv("ENVIRONMENT") != "production"
        else "prod_sensitive_dwh_stg_userdata_read"
    )
    op.grant_on_schema(
        (
            "test_sensitive_dwh_stg_userdata_all"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_sensitive_dwh_stg_userdata_all"
        ),
        "STG_USERDATA",
    )
    op.grant_on_schema(
        (
            "test_sensitive_dwh_stg_userdata_write"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_sensitive_dwh_stg_userdata_write"
        ),
        "STG_USERDATA",
    )
    op.grant_on_schema(
        (
            "test_sensitive_dwh_stg_userdata_read"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_sensitive_dwh_stg_userdata_read"
        ),
        "STG_USERDATA",
    )
    op.grant_on_table(
        "test_dwh_dm_rental_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_dm_rental_read",
        ['SELECT'],
        '"DM_RENTAL".dm_strike',
    )
    op.grant_on_table(
        "test_dwh_dm_rental_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_dm_rental_all",
        ['ALL'],
        '"DM_RENTAL".dm_strike',
    )
    op.grant_on_table(
        "test_dwh_dm_rental_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_dm_rental_write",
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"DM_RENTAL".dm_strike',
    )
    op.grant_on_table(
        "test_dwh_dm_timetable_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_dm_timetable_write",
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"DM_TIMETABLE".dm_timetable_act',
    )
    op.grant_on_table(
        "test_dwh_dm_timetable_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_dm_timetable_read",
        ['SELECT'],
        '"DM_TIMETABLE".dm_timetable_act',
    )
    op.grant_on_table(
        "test_dwh_dm_timetable_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_dm_timetable_all",
        ['ALL'],
        '"DM_TIMETABLE".dm_timetable_act',
    )
    op.grant_on_table(
        "test_dwh_dm_user_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_dm_user_write",
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"DM_USER".union_member_card',
    )
    op.grant_on_table(
        "test_dwh_dm_user_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_dm_user_all",
        ['ALL'],
        '"DM_USER".union_member_card',
    )
    op.grant_on_table(
        "test_dwh_dm_user_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_dm_user_read",
        ['SELECT'],
        '"DM_USER".union_member_card',
    )
    op.grant_on_table(
        "test_dwh_dwh_user_info_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_dwh_user_info_all",
        ['ALL'],
        '"DWH_USER_INFO".encrypted_info',
    )
    op.grant_on_table(
        "test_dwh_dwh_user_info_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_dwh_user_info_write",
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"DWH_USER_INFO".encrypted_info',
    )
    op.grant_on_table(
        "test_dwh_dwh_user_info_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_dwh_user_info_read",
        ['SELECT'],
        '"DWH_USER_INFO".encrypted_info',
    )
    op.grant_on_table(
        "test_dwh_ods_social_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_social_read",
        ['SELECT'],
        '"ODS_SOCIAL".git_hub',
    )
    op.grant_on_table(
        "test_dwh_ods_social_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_social_write",
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"ODS_SOCIAL".git_hub',
    )
    op.grant_on_table(
        "test_dwh_ods_social_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_social_all",
        ['ALL'],
        '"ODS_SOCIAL".git_hub',
    )
    op.grant_on_table(
        "test_dwh_ods_userdata_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_userdata_read",
        ['SELECT'],
        '"ODS_USERDATA".card',
    )
    op.grant_on_table(
        "test_dwh_ods_userdata_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_userdata_all",
        ['ALL'],
        '"ODS_USERDATA".card',
    )
    op.grant_on_table(
        "test_dwh_ods_userdata_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_userdata_write",
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"ODS_USERDATA".card',
    )
    op.grant_on_table(
        "test_dwh_ods_userdata_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_userdata_read",
        ['SELECT'],
        '"ODS_USERDATA".rzd',
    )
    op.grant_on_table(
        "test_dwh_ods_userdata_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_userdata_all",
        ['ALL'],
        '"ODS_USERDATA".rzd',
    )
    op.grant_on_table(
        "test_dwh_ods_userdata_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_userdata_write",
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"ODS_USERDATA".rzd',
    )
    op.grant_on_table(
        "test_dwh_ods_userdata_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_userdata_read",
        ['SELECT'],
        '"ODS_USERDATA".status',
    )
    op.grant_on_table(
        "test_dwh_ods_userdata_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_userdata_all",
        ['ALL'],
        '"ODS_USERDATA".status',
    )
    op.grant_on_table(
        "test_dwh_ods_userdata_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_userdata_write",
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"ODS_USERDATA".status',
    )
    op.add_column(
        'info_keys',
        sa.Column('created', sa.DateTime(), nullable=False, comment='Дата создания/обновления ключа'),
        schema='STG_USERDATA',
    )
    op.grant_on_table(
        (
            "test_sensitive_dwh_stg_userdata_all"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_sensitive_dwh_stg_userdata_all"
        ),
        ['ALL'],
        '"STG_USERDATA".info_keys',
    )
    op.grant_on_table(
        (
            "test_sensitive_dwh_stg_userdata_read"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_sensitive_dwh_stg_userdata_read"
        ),
        ['SELECT'],
        '"STG_USERDATA".info_keys',
    )
    op.grant_on_table(
        (
            "test_sensitive_dwh_stg_userdata_write"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_sensitive_dwh_stg_userdata_write"
        ),
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"STG_USERDATA".info_keys',
    )
    op.drop_table('encrypted_info', schema='STG_USERDATA')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'encrypted_info',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='Идентификатор зашифрованной записи'),
        sa.Column('param_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Идентификатор параметра'),
        sa.Column(
            'source_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Идентификатор источника данных'
        ),
        sa.Column(
            'owner_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Идентификатор владельца данных'
        ),
        sa.Column(
            'value', postgresql.BYTEA(), autoincrement=False, nullable=True, comment='Зашифрованное значение параметра'
        ),
        sa.Column(
            'create_ts', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Время создания записи'
        ),
        sa.Column(
            'modify_ts',
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
            comment='Время последнего изменения записи',
        ),
        sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='Флаг удаления записи'),
        sa.PrimaryKeyConstraint('id', name=op.f('encrypted_info_pkey')),
        schema='STG_USERDATA',
    )
    op.revoke_on_table(
        (
            "test_sensitive_dwh_stg_userdata_write"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_sensitive_dwh_stg_userdata_write"
        ),
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"STG_USERDATA".info_keys',
    )
    op.revoke_on_table(
        (
            "test_sensitive_dwh_stg_userdata_read"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_sensitive_dwh_stg_userdata_read"
        ),
        ['SELECT'],
        '"STG_USERDATA".info_keys',
    )
    op.revoke_on_table(
        (
            "test_sensitive_dwh_stg_userdata_all"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_sensitive_dwh_stg_userdata_all"
        ),
        ['ALL'],
        '"STG_USERDATA".info_keys',
    )
    op.drop_column('info_keys', 'created', schema='STG_USERDATA')
    op.revoke_on_table(
        "test_dwh_ods_userdata_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_userdata_write",
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"ODS_USERDATA".status',
    )
    op.revoke_on_table(
        "test_dwh_ods_userdata_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_userdata_all",
        ['ALL'],
        '"ODS_USERDATA".status',
    )
    op.revoke_on_table(
        "test_dwh_ods_userdata_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_userdata_read",
        ['SELECT'],
        '"ODS_USERDATA".status',
    )
    op.revoke_on_table(
        "test_dwh_ods_userdata_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_userdata_write",
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"ODS_USERDATA".rzd',
    )
    op.revoke_on_table(
        "test_dwh_ods_userdata_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_userdata_all",
        ['ALL'],
        '"ODS_USERDATA".rzd',
    )
    op.revoke_on_table(
        "test_dwh_ods_userdata_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_userdata_read",
        ['SELECT'],
        '"ODS_USERDATA".rzd',
    )
    op.revoke_on_table(
        "test_dwh_ods_userdata_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_userdata_write",
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"ODS_USERDATA".card',
    )
    op.revoke_on_table(
        "test_dwh_ods_userdata_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_userdata_all",
        ['ALL'],
        '"ODS_USERDATA".card',
    )
    op.revoke_on_table(
        "test_dwh_ods_userdata_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_userdata_read",
        ['SELECT'],
        '"ODS_USERDATA".card',
    )
    op.revoke_on_table(
        "test_dwh_ods_social_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_social_all",
        ['ALL'],
        '"ODS_SOCIAL".git_hub',
    )
    op.revoke_on_table(
        "test_dwh_ods_social_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_social_write",
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"ODS_SOCIAL".git_hub',
    )
    op.revoke_on_table(
        "test_dwh_ods_social_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_ods_social_read",
        ['SELECT'],
        '"ODS_SOCIAL".git_hub',
    )
    op.revoke_on_table(
        "test_dwh_dwh_user_info_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_dwh_user_info_read",
        ['SELECT'],
        '"DWH_USER_INFO".encrypted_info',
    )
    op.revoke_on_table(
        "test_dwh_dwh_user_info_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_dwh_user_info_write",
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"DWH_USER_INFO".encrypted_info',
    )
    op.revoke_on_table(
        "test_dwh_dwh_user_info_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_dwh_user_info_all",
        ['ALL'],
        '"DWH_USER_INFO".encrypted_info',
    )
    op.revoke_on_table(
        "test_dwh_dm_user_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_dm_user_read",
        ['SELECT'],
        '"DM_USER".union_member_card',
    )
    op.revoke_on_table(
        "test_dwh_dm_user_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_dm_user_all",
        ['ALL'],
        '"DM_USER".union_member_card',
    )
    op.revoke_on_table(
        "test_dwh_dm_user_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_dm_user_write",
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"DM_USER".union_member_card',
    )
    op.revoke_on_table(
        "test_dwh_dm_timetable_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_dm_timetable_all",
        ['ALL'],
        '"DM_TIMETABLE".dm_timetable_act',
    )
    op.revoke_on_table(
        "test_dwh_dm_timetable_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_dm_timetable_read",
        ['SELECT'],
        '"DM_TIMETABLE".dm_timetable_act',
    )
    op.revoke_on_table(
        "test_dwh_dm_timetable_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_dm_timetable_write",
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"DM_TIMETABLE".dm_timetable_act',
    )
    op.revoke_on_table(
        "test_dwh_dm_rental_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_dm_rental_write",
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"DM_RENTAL".dm_strike',
    )
    op.revoke_on_table(
        "test_dwh_dm_rental_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_dm_rental_all",
        ['ALL'],
        '"DM_RENTAL".dm_strike',
    )
    op.revoke_on_table(
        "test_dwh_dm_rental_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_dm_rental_read",
        ['SELECT'],
        '"DM_RENTAL".dm_strike',
    )
    op.revoke_on_schema(
        (
            "test_sensitive_dwh_stg_userdata_read"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_sensitive_dwh_stg_userdata_read"
        ),
        "STG_USERDATA",
    )
    op.revoke_on_schema(
        (
            "test_sensitive_dwh_stg_userdata_write"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_sensitive_dwh_stg_userdata_write"
        ),
        "STG_USERDATA",
    )
    op.revoke_on_schema(
        (
            "test_sensitive_dwh_stg_userdata_all"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_sensitive_dwh_stg_userdata_all"
        ),
        "STG_USERDATA",
    )
    op.delete_group(
        "test_sensitive_dwh_stg_userdata_read"
        if os.getenv("ENVIRONMENT") != "production"
        else "prod_sensitive_dwh_stg_userdata_read"
    )
    op.delete_group(
        "test_sensitive_dwh_stg_userdata_write"
        if os.getenv("ENVIRONMENT") != "production"
        else "prod_sensitive_dwh_stg_userdata_write"
    )
    op.delete_group(
        "test_sensitive_dwh_stg_userdata_all"
        if os.getenv("ENVIRONMENT") != "production"
        else "prod_sensitive_dwh_stg_userdata_all"
    )
    # ### end Alembic commands ###
