"""union_member_add_rows

Revision ID: 137dc7c08814
Revises: d5063f55a1f4
Create Date: 2025-12-23 15:02:50.657876

"""

import os

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '137dc7c08814'
down_revision = 'd5063f55a1f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'dm_lecturer_comment_act',
        'mark_weighted',
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_comment='Взвешенная оценка преподавателя',
        existing_nullable=False,
        existing_server_default=sa.text("'0'::double precision"),
        schema='DM_RATING',
    )
    op.alter_column(
        'dm_lecturer_comment_act',
        'mark_kindness_weighted',
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_comment='Взвешенная доброта преподавателя',
        existing_nullable=False,
        existing_server_default=sa.text("'0'::double precision"),
        schema='DM_RATING',
    )
    op.alter_column(
        'dm_lecturer_comment_act',
        'mark_clarity_weighted',
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_comment='Взвешенная понятность преподавателя',
        existing_nullable=False,
        existing_server_default=sa.text("'0'::double precision"),
        schema='DM_RATING',
    )
    op.alter_column(
        'dm_lecturer_comment_act',
        'mark_freebie_weighted',
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_comment='Взвешенная халявность преподавателя',
        existing_nullable=False,
        existing_server_default=sa.text("'0'::double precision"),
        schema='DM_RATING',
    )
    op.create_table_comment('dm_strike', '\n    Витрина страйки\n    ', existing_comment=None, schema='DM_RENTAL')
    op.create_index('lecturer_ts_idx', 'lecturer', ['valid_from_dt', 'valid_to_dt'], unique=False, schema='DWH_RATING')
    op.alter_column(
        'git_hub',
        'issue_id',
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        existing_comment='Идентификатор issue',
        existing_nullable=True,
        schema='ODS_SOCIAL',
    )
    op.alter_column(
        'git_hub',
        'user_id',
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        existing_comment='Идентификатор пользователя открывшего issue',
        existing_nullable=True,
        schema='ODS_SOCIAL',
    )
    op.alter_column(
        'git_hub',
        'repository_id',
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        existing_comment='Идентификатор репозитория',
        existing_nullable=True,
        schema='ODS_SOCIAL',
    )
    op.alter_column(
        'git_hub',
        'assignee_id',
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        existing_comment='Идентификатор назначенного исполнителем issue',
        existing_nullable=True,
        schema='ODS_SOCIAL',
    )
    op.alter_column(
        'git_hub',
        'assignee_login',
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        existing_comment='Логин назначенного исполнителем issue',
        existing_nullable=True,
        schema='ODS_SOCIAL',
    )
    op.alter_column(
        'git_hub',
        'organization_id',
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        existing_comment='Идентификатор организации',
        existing_nullable=False,
        schema='ODS_SOCIAL',
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'git_hub',
        'organization_id',
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        existing_comment='Идентификатор организации',
        existing_nullable=False,
        schema='ODS_SOCIAL',
    )
    op.alter_column(
        'git_hub',
        'assignee_login',
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        existing_comment='Логин назначенного исполнителем issue',
        existing_nullable=True,
        schema='ODS_SOCIAL',
    )
    op.alter_column(
        'git_hub',
        'assignee_id',
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        existing_comment='Идентификатор назначенного исполнителем issue',
        existing_nullable=True,
        schema='ODS_SOCIAL',
    )
    op.alter_column(
        'git_hub',
        'repository_id',
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        existing_comment='Идентификатор репозитория',
        existing_nullable=True,
        schema='ODS_SOCIAL',
    )
    op.alter_column(
        'git_hub',
        'user_id',
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        existing_comment='Идентификатор пользователя открывшего issue',
        existing_nullable=True,
        schema='ODS_SOCIAL',
    )
    op.alter_column(
        'git_hub',
        'issue_id',
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        existing_comment='Идентификатор issue',
        existing_nullable=True,
        schema='ODS_SOCIAL',
    )
    op.drop_index('lecturer_ts_idx', table_name='lecturer', schema='DWH_RATING')
    op.drop_table_comment('dm_strike', existing_comment='\n    Витрина страйки\n    ', schema='DM_RENTAL')
    op.alter_column(
        'dm_lecturer_comment_act',
        'mark_freebie_weighted',
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_comment='Взвешенная халявность преподавателя',
        existing_nullable=False,
        existing_server_default=sa.text("'0'::double precision"),
        schema='DM_RATING',
    )
    op.alter_column(
        'dm_lecturer_comment_act',
        'mark_clarity_weighted',
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_comment='Взвешенная понятность преподавателя',
        existing_nullable=False,
        existing_server_default=sa.text("'0'::double precision"),
        schema='DM_RATING',
    )
    op.alter_column(
        'dm_lecturer_comment_act',
        'mark_kindness_weighted',
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_comment='Взвешенная доброта преподавателя',
        existing_nullable=False,
        existing_server_default=sa.text("'0'::double precision"),
        schema='DM_RATING',
    )
    op.alter_column(
        'dm_lecturer_comment_act',
        'mark_weighted',
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_comment='Взвешенная оценка преподавателя',
        existing_nullable=False,
        existing_server_default=sa.text("'0'::double precision"),
        schema='DM_RATING',
    )
    # ### end Alembic commands ###
