"""new_cdm_migrations

Revision ID: fbf37c061802
Revises: 5edf7206774e
Create Date: 2025-04-07 14:18:10.785099

"""
from alembic import op
import sqlalchemy as sa
import os


# revision identifiers, used by Alembic.
revision = 'fbf37c061802'
down_revision = '5edf7206774e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecturer', sa.Column('shitcol', sa.String(), nullable=False), schema='DWH_RATING')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lecturer', 'shitcol', schema='DWH_RATING')
    # ### end Alembic commands ###
