"""union_member_add_rows

Revision ID: e52300ce0b4c
Revises: 137dc7c08814
Create Date: 2025-12-23 17:26:06.169058

"""

import os

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'e52300ce0b4c'
down_revision = '137dc7c08814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'union_member',
        'academic_level_translated',
        existing_type=sa.VARCHAR(),
        comment='Уровень образования (бакалавриат/магистратура/аспирантура) на английском',
        existing_comment='Уровень образования (бакалавриат/магистратура/аспирантура на английском)',
        existing_nullable=True,
        schema='STG_UNION_MEMBER',
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'union_member',
        'academic_level_translated',
        existing_type=sa.VARCHAR(),
        comment='Уровень образования (бакалавриат/магистратура/аспирантура на английском)',
        existing_comment='Уровень образования (бакалавриат/магистратура/аспирантура) на английском',
        existing_nullable=True,
        schema='STG_UNION_MEMBER',
    )
    # ### end Alembic commands ###
