"""user_view_type_fix

Revision ID: 1a5ed9901423
Revises: ac67f7273994
Create Date: 2026-02-03 18:53:36.874014

"""
import os

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '1a5ed9901423'
down_revision = 'ac67f7273994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profcomff_team', sa.Column('type', sa.String(), nullable=True), schema='STG_GITHUB')
    op.add_column('profcomff_team', sa.Column('organization_id', sa.Integer(), nullable=True), schema='STG_GITHUB')
    op.add_column('profcomff_team_member', sa.Column('user_view_type', sa.String(), nullable=True), schema='STG_GITHUB')
    op.add_column('profcomff_team_repo', sa.Column('owner_user_view_type', sa.String(), nullable=True), schema='STG_GITHUB')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profcomff_team_repo', 'owner_user_view_type', schema='STG_GITHUB')
    op.drop_column('profcomff_team_member', 'user_view_type', schema='STG_GITHUB')
    op.drop_column('profcomff_team', 'organization_id', schema='STG_GITHUB')
    op.drop_column('profcomff_team', 'type', schema='STG_GITHUB')
    # ### end Alembic commands ###
