"""init

Revision ID: 6e015c24110c
Revises: 
Create Date: 2023-08-24 23:10:16.757279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e015c24110c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_table_schema("STG_UNION_MEMBER")
    op.create_table_schema("STG_TEST")
    op.create_table(
        'test', sa.Column('id', sa.Integer(), nullable=False), sa.PrimaryKeyConstraint('id'), schema='STG_TEST'
    )
    op.create_table(
        'union_member',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('type_of_learning', sa.String(), nullable=False),
        sa.Column('rzd_status', sa.String(), nullable=False),
        sa.Column('academic_level', sa.String(), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('faculty', sa.String(), nullable=False),
        sa.Column('first_name', sa.String(), nullable=False),
        sa.Column('last_name', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('date_of_birth', sa.String(), nullable=False),
        sa.Column('phone_number', sa.String(), nullable=False),
        sa.Column('image', sa.String(), nullable=False),
        sa.Column('rzd_datetime', sa.String(), nullable=False),
        sa.Column('rzd_number', sa.String(), nullable=False),
        sa.Column('grade_level', sa.Integer(), nullable=False),
        sa.Column('has_student_id', sa.Boolean(), nullable=False),
        sa.Column('entry_date', sa.String(), nullable=False),
        sa.Column('status_gain_date', sa.String(), nullable=False),
        sa.Column('card_id', sa.Integer(), nullable=False),
        sa.Column('card_status', sa.String(), nullable=False),
        sa.Column('card_date', sa.String(), nullable=False),
        sa.Column('card_number', sa.String(), nullable=False),
        sa.Column('card_user', sa.String(), nullable=False),
        sa.Column('card', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        schema='STG_UNION_MEMBER',
    )
    op.create_group("dwh_stg_test_read")
    op.create_group("dwh_stg_test_write")
    op.create_group("dwh_stg_test_all")
    op.grant_rights("dwh_stg_union_member_read", "['SELECT', 'SELECT']", '"STG_UNION_MEMBER".union_member')
    op.grant_rights("dwh_stg_union_member_read", "['SELECT', 'SELECT']", '"STG_TEST".test')
    op.grant_rights(
        "dwh_stg_union_member_write",
        "['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'SELECT', 'UPDATE', 'DELETE', 'TRUNCATE']",
        '"STG_UNION_MEMBER".union_member',
    )
    op.grant_rights(
        "dwh_stg_union_member_write",
        "['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'SELECT', 'UPDATE', 'DELETE', 'TRUNCATE']",
        '"STG_TEST".test',
    )
    op.grant_rights("dwh_stg_union_member_all", "['ALL', 'ALL']", '"STG_UNION_MEMBER".union_member')
    op.grant_rights("dwh_stg_union_member_all", "['ALL', 'ALL']", '"STG_TEST".test')
    op.grant_rights("dwh_stg_test_read", "['SELECT', 'SELECT']", '"STG_UNION_MEMBER".union_member')
    op.grant_rights("dwh_stg_test_read", "['SELECT', 'SELECT']", '"STG_TEST".test')
    op.grant_rights(
        "dwh_stg_test_write",
        "['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'SELECT', 'UPDATE', 'DELETE', 'TRUNCATE']",
        '"STG_UNION_MEMBER".union_member',
    )
    op.grant_rights(
        "dwh_stg_test_write",
        "['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'SELECT', 'UPDATE', 'DELETE', 'TRUNCATE']",
        '"STG_TEST".test',
    )
    op.grant_rights("dwh_stg_test_all", "['ALL', 'ALL']", '"STG_UNION_MEMBER".union_member')
    op.grant_rights("dwh_stg_test_all", "['ALL', 'ALL']", '"STG_TEST".test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.revoke_rights("dwh_stg_test_all", "['ALL', 'ALL']", '"STG_TEST".test')
    op.revoke_rights("dwh_stg_test_all", "['ALL', 'ALL']", '"STG_UNION_MEMBER".union_member')
    op.revoke_rights(
        "dwh_stg_test_write",
        "['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'SELECT', 'UPDATE', 'DELETE', 'TRUNCATE']",
        '"STG_TEST".test',
    )
    op.revoke_rights(
        "dwh_stg_test_write",
        "['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'SELECT', 'UPDATE', 'DELETE', 'TRUNCATE']",
        '"STG_UNION_MEMBER".union_member',
    )
    op.revoke_rights("dwh_stg_test_read", "['SELECT', 'SELECT']", '"STG_TEST".test')
    op.revoke_rights("dwh_stg_test_read", "['SELECT', 'SELECT']", '"STG_UNION_MEMBER".union_member')
    op.revoke_rights("dwh_stg_union_member_all", "['ALL', 'ALL']", '"STG_TEST".test')
    op.revoke_rights("dwh_stg_union_member_all", "['ALL', 'ALL']", '"STG_UNION_MEMBER".union_member')
    op.revoke_rights(
        "dwh_stg_union_member_write",
        "['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'SELECT', 'UPDATE', 'DELETE', 'TRUNCATE']",
        '"STG_TEST".test',
    )
    op.revoke_rights(
        "dwh_stg_union_member_write",
        "['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'SELECT', 'UPDATE', 'DELETE', 'TRUNCATE']",
        '"STG_UNION_MEMBER".union_member',
    )
    op.revoke_rights("dwh_stg_union_member_read", "['SELECT', 'SELECT']", '"STG_TEST".test')
    op.revoke_rights("dwh_stg_union_member_read", "['SELECT', 'SELECT']", '"STG_UNION_MEMBER".union_member')
    op.drop_table('union_member', schema='STG_UNION_MEMBER')
    op.drop_table('test', schema='STG_TEST')
    op.delete_group("dwh_stg_test_all")
    op.delete_group("dwh_stg_test_write")
    op.delete_group("dwh_stg_test_read")
    op.drop_table_schema("STG_TEST")
    op.drop_table_schema("STG_UNION_MEMBER")
    op.create_table(
        'alembic_version',
        sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('version_num', name='alembic_version_pkc'),
    )
    # ### end Alembic commands ###
