"""integrity_fix #1

Revision ID: 840547068d8c
Revises: 4892e78eb989
Create Date: 2024-05-04 16:32:43.419484

"""

import os

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '840547068d8c'
down_revision = '4892e78eb989'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.revoke_on_table(
        ("test_dwh_stg_social_read" if os.getenv("ENVIRONMENT") != "production" else "prod_test_dwh_stg_social_read"),
        ['SELECT'],
        '"STG_SOCIAL".vk_groups',
    )
    op.revoke_on_table(
        ("test_dwh_stg_social_write" if os.getenv("ENVIRONMENT") != "production" else "prod_test_dwh_stg_social_write"),
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"STG_SOCIAL".vk_groups',
    )
    op.revoke_on_table(
        "test_dwh_stg_social_all" if os.getenv("ENVIRONMENT") != "production" else "prod_test_dwh_stg_social_all",
        [
            'INSERT',
            'SELECT',
            'UPDATE',
            'DELETE',
            'TRUNCATE',
            'REFERENCES',
            'TRIGGER',
        ],
        '"STG_SOCIAL".vk_groups',
    )
    op.revoke_on_table(
        (
            "test_dwh_stg_timetable_read"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_test_dwh_stg_timetable_read"
        ),
        [
            'SELECT',
        ],
        '"STG_TIMETABLE".raw_html_old',
    )
    op.revoke_on_table(
        (
            "test_dwh_stg_timetable_write"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_test_dwh_stg_timetable_write"
        ),
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"STG_TIMETABLE".raw_html_old',
    )
    op.revoke_on_table(
        (
            "test_dwh_stg_timetable_all"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_test_dwh_stg_timetable_all"
        ),
        [
            'INSERT',
            'SELECT',
            'UPDATE',
            'DELETE',
            'TRUNCATE',
            'REFERENCES',
            'TRIGGER',
        ],
        '"STG_TIMETABLE".raw_html_old',
    )
    op.drop_table('raw_html_old', schema='STG_TIMETABLE')
    op.drop_table('vk_groups', schema='STG_SOCIAL')
    op.create_table_schema("STG_ACHIEVEMENT")
    op.create_table(
        'achievement',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('picture', sa.String(), nullable=False),
        sa.Column('owner_user_id', sa.Integer(), nullable=False),
        sa.Column('create_ts', sa.DateTime(), nullable=False),
        sa.Column('update_ts', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        schema='STG_ACHIEVEMENT',
    )
    op.create_table(
        'achievement_receiver',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('achievement_id', sa.Integer(), nullable=False),
        sa.Column('create_ts', sa.DateTime(), nullable=False),
        sa.Column('update_ts', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        schema='STG_ACHIEVEMENT',
    )
    op.create_table(
        'dynamic_option',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('create_ts', sa.DateTime(), nullable=False),
        sa.Column('value_integer', sa.Integer(), nullable=False),
        sa.Column('value_string', sa.String(), nullable=False),
        sa.Column('value_double', sa.Double(), nullable=False),
        sa.Column('update_ts', sa.DateTime(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        schema='STG_AUTH',
    )
    op.create_table(
        'create_group_request',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('valid_ts', sa.DateTime(), nullable=False),
        sa.Column('create_ts', sa.DateTime(), nullable=False),
        sa.Column('owner_id', sa.Integer(), nullable=False),
        sa.Column('mapped_group_id', sa.Integer(), nullable=False),
        sa.Column('secret_key', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        schema='STG_SOCIAL',
    )
    op.create_table(
        'group',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('update_ts', sa.DateTime(), nullable=False),
        sa.Column('create_ts', sa.DateTime(), nullable=False),
        sa.Column('last_active_ts', sa.DateTime(), nullable=False),
        sa.Column('owner_id', sa.Integer(), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.Column('type', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        schema='STG_SOCIAL',
    )
    op.create_table(
        'telegram_channel',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('channel_id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        schema='STG_SOCIAL',
    )
    op.create_table(
        'telegram_chat',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('chat_id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        schema='STG_SOCIAL',
    )
    op.create_table(
        'vk_chat',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('peer_id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        schema='STG_SOCIAL',
    )
    op.create_table(
        'vk_group',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('group_id', sa.Integer(), nullable=False),
        sa.Column('confirmation_token', sa.String(), nullable=False),
        sa.Column('secret_key', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        schema='STG_SOCIAL',
    )
    op.create_group(
        "test_dwh_stg_achievement_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_achievement_read"
    )
    op.create_group(
        "test_dwh_stg_achievement_write"
        if os.getenv("ENVIRONMENT") != "production"
        else "prod_dwh_stg_achievement_write"
    )
    op.create_group(
        "test_dwh_stg_achievement_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_achievement_all"
    )
    op.grant_on_schema(
        (
            "test_dwh_stg_achievement_read"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_dwh_stg_achievement_read"
        ),
        "STG_ACHIEVEMENT",
    )
    op.grant_on_schema(
        (
            "test_dwh_stg_achievement_write"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_dwh_stg_achievement_write"
        ),
        "STG_ACHIEVEMENT",
    )
    op.grant_on_schema(
        "test_dwh_stg_achievement_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_achievement_all",
        "STG_ACHIEVEMENT",
    )
    op.grant_on_table(
        (
            "test_dwh_stg_achievement_read"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_dwh_stg_achievement_read"
        ),
        ['SELECT'],
        '"STG_ACHIEVEMENT".achievement',
    )
    op.grant_on_table(
        (
            "test_dwh_stg_achievement_read"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_dwh_stg_achievement_read"
        ),
        ['SELECT'],
        '"STG_ACHIEVEMENT".achievement_receiver',
    )
    op.grant_on_table(
        (
            "test_dwh_stg_achievement_write"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_dwh_stg_achievement_write"
        ),
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"STG_ACHIEVEMENT".achievement',
    )
    op.grant_on_table(
        (
            "test_dwh_stg_achievement_write"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_dwh_stg_achievement_write"
        ),
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"STG_ACHIEVEMENT".achievement_receiver',
    )
    op.grant_on_table(
        "test_dwh_stg_achievement_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_achievement_all",
        ['ALL'],
        '"STG_ACHIEVEMENT".achievement',
    )
    op.grant_on_table(
        "test_dwh_stg_achievement_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_achievement_all",
        ['ALL'],
        '"STG_ACHIEVEMENT".achievement_receiver',
    )
    op.grant_on_table(
        "test_dwh_stg_social_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_social_read",
        ['SELECT'],
        '"STG_SOCIAL".group',
    )
    op.grant_on_table(
        "test_dwh_stg_social_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_social_write",
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"STG_SOCIAL".group',
    )
    op.grant_on_table(
        "test_dwh_stg_social_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_social_all",
        ['ALL'],
        '"STG_SOCIAL".group',
    )
    op.grant_on_table(
        "test_dwh_stg_social_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_social_read",
        ['SELECT'],
        '"STG_SOCIAL".create_group_request',
    )
    op.grant_on_table(
        "test_dwh_stg_social_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_social_write",
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"STG_SOCIAL".create_group_request',
    )
    op.grant_on_table(
        "test_dwh_stg_social_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_social_all",
        ['ALL'],
        '"STG_SOCIAL".create_group_request',
    )
    op.grant_on_table(
        "test_dwh_stg_social_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_social_read",
        ['SELECT'],
        '"STG_SOCIAL".vk_group',
    )
    op.grant_on_table(
        "test_dwh_stg_social_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_social_write",
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"STG_SOCIAL".vk_group',
    )
    op.grant_on_table(
        "test_dwh_stg_social_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_social_all",
        ['ALL'],
        '"STG_SOCIAL".vk_group',
    )
    op.grant_on_table(
        "test_dwh_stg_social_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_social_read",
        ['SELECT'],
        '"STG_SOCIAL".telegram_channel',
    )
    op.grant_on_table(
        "test_dwh_stg_social_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_social_write",
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"STG_SOCIAL".telegram_channel',
    )
    op.grant_on_table(
        "test_dwh_stg_social_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_social_all",
        ['ALL'],
        '"STG_SOCIAL".telegram_channel',
    )
    op.grant_on_table(
        "test_dwh_stg_social_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_social_read",
        ['SELECT'],
        '"STG_SOCIAL".telegram_chat',
    )
    op.grant_on_table(
        "test_dwh_stg_social_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_social_write",
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"STG_SOCIAL".telegram_chat',
    )
    op.grant_on_table(
        "test_dwh_stg_social_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_social_all",
        ['ALL'],
        '"STG_SOCIAL".telegram_chat',
    )
    op.grant_on_table(
        "test_dwh_stg_social_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_social_read",
        ['SELECT'],
        '"STG_SOCIAL".vk_chat',
    )
    op.grant_on_table(
        "test_dwh_stg_social_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_social_write",
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"STG_SOCIAL".vk_chat',
    )
    op.grant_on_table(
        "test_dwh_stg_social_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_social_all",
        ['ALL'],
        '"STG_SOCIAL".vk_chat',
    )
    op.grant_on_table(
        "test_dwh_stg_auth_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_auth_read",
        ['SELECT'],
        '"STG_AUTH".dynamic_option',
    )
    op.grant_on_table(
        "test_dwh_stg_auth_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_auth_write",
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"STG_AUTH".dynamic_option',
    )
    op.grant_on_table(
        "test_dwh_stg_auth_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_auth_all",
        ['ALL'],
        '"STG_AUTH".dynamic_option',
    )
    op.add_column('scope', sa.Column('button_id', sa.Integer(), nullable=False), schema='STG_SERVICES')
    op.add_column('scope', sa.Column('is_required', sa.Boolean(), nullable=False), schema='STG_SERVICES')
    op.add_column('webhook_storage', sa.Column('event_ts', sa.DateTime(), nullable=False), schema='STG_SOCIAL')
    op.alter_column('raw_html', 'url', existing_type=sa.VARCHAR(length=256), nullable=False, schema='STG_TIMETABLE')
    op.alter_column('raw_html', 'raw_html', existing_type=sa.TEXT(), nullable=False, schema='STG_TIMETABLE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.revoke_on_table(
        "test_dwh_stg_auth_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_auth_all",
        ['ALL'],
        '"STG_AUTH".dynamic_option',
    )
    op.revoke_on_table(
        "test_dwh_stg_auth_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_auth_write",
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"STG_AUTH".dynamic_option',
    )
    op.revoke_on_table(
        "test_dwh_stg_auth_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_auth_read",
        ['SELECT'],
        '"STG_AUTH".dynamic_option',
    )
    op.revoke_on_table(
        "test_dwh_stg_social_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_social_all",
        ['ALL'],
        '"STG_SOCIAL".vk_chat',
    )
    op.revoke_on_table(
        "test_dwh_stg_social_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_social_write",
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"STG_SOCIAL".vk_chat',
    )
    op.revoke_on_table(
        "test_dwh_stg_social_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_social_read",
        ['SELECT'],
        '"STG_SOCIAL".vk_chat',
    )
    op.revoke_on_table(
        "test_dwh_stg_social_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_social_all",
        ['ALL'],
        '"STG_SOCIAL".telegram_chat',
    )
    op.revoke_on_table(
        "test_dwh_stg_social_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_social_write",
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"STG_SOCIAL".telegram_chat',
    )
    op.revoke_on_table(
        "test_dwh_stg_social_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_social_read",
        ['SELECT'],
        '"STG_SOCIAL".telegram_chat',
    )
    op.revoke_on_table(
        "test_dwh_stg_social_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_social_all",
        ['ALL'],
        '"STG_SOCIAL".telegram_channel',
    )
    op.revoke_on_table(
        "test_dwh_stg_social_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_social_write",
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"STG_SOCIAL".telegram_channel',
    )
    op.revoke_on_table(
        "test_dwh_stg_social_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_social_read",
        ['SELECT'],
        '"STG_SOCIAL".telegram_channel',
    )
    op.revoke_on_table(
        "test_dwh_stg_social_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_social_all",
        ['ALL'],
        '"STG_SOCIAL".vk_group',
    )
    op.revoke_on_table(
        "test_dwh_stg_social_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_social_write",
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"STG_SOCIAL".vk_group',
    )
    op.revoke_on_table(
        "test_dwh_stg_social_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_social_read",
        ['SELECT'],
        '"STG_SOCIAL".vk_group',
    )
    op.revoke_on_table(
        "test_dwh_stg_social_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_social_all",
        ['ALL'],
        '"STG_SOCIAL".create_group_request',
    )
    op.revoke_on_table(
        "test_dwh_stg_social_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_social_write",
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"STG_SOCIAL".create_group_request',
    )
    op.revoke_on_table(
        "test_dwh_stg_social_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_social_read",
        ['SELECT'],
        '"STG_SOCIAL".create_group_request',
    )
    op.revoke_on_table(
        "test_dwh_stg_social_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_social_all",
        ['ALL'],
        '"STG_SOCIAL".group',
    )
    op.revoke_on_table(
        "test_dwh_stg_social_write" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_social_write",
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"STG_SOCIAL".group',
    )
    op.revoke_on_table(
        "test_dwh_stg_social_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_social_read",
        ['SELECT'],
        '"STG_SOCIAL".group',
    )
    op.revoke_on_table(
        "test_dwh_stg_achievement_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_achievement_all",
        ['ALL'],
        '"STG_ACHIEVEMENT".achievement_receiver',
    )
    op.revoke_on_table(
        "test_dwh_stg_achievement_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_achievement_all",
        ['ALL'],
        '"STG_ACHIEVEMENT".achievement',
    )
    op.revoke_on_table(
        (
            "test_dwh_stg_achievement_write"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_dwh_stg_achievement_write"
        ),
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"STG_ACHIEVEMENT".achievement_receiver',
    )
    op.revoke_on_table(
        (
            "test_dwh_stg_achievement_write"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_dwh_stg_achievement_write"
        ),
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"STG_ACHIEVEMENT".achievement',
    )
    op.revoke_on_table(
        (
            "test_dwh_stg_achievement_read"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_dwh_stg_achievement_read"
        ),
        ['SELECT'],
        '"STG_ACHIEVEMENT".achievement_receiver',
    )
    op.revoke_on_table(
        (
            "test_dwh_stg_achievement_read"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_dwh_stg_achievement_read"
        ),
        ['SELECT'],
        '"STG_ACHIEVEMENT".achievement',
    )
    op.revoke_on_schema(
        "test_dwh_stg_achievement_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_achievement_all",
        "STG_ACHIEVEMENT",
    )
    op.revoke_on_schema(
        (
            "test_dwh_stg_achievement_write"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_dwh_stg_achievement_write"
        ),
        "STG_ACHIEVEMENT",
    )
    op.revoke_on_schema(
        (
            "test_dwh_stg_achievement_read"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_dwh_stg_achievement_read"
        ),
        "STG_ACHIEVEMENT",
    )
    op.drop_table('vk_group', schema='STG_SOCIAL')
    op.drop_table('vk_chat', schema='STG_SOCIAL')
    op.drop_table('telegram_chat', schema='STG_SOCIAL')
    op.drop_table('telegram_channel', schema='STG_SOCIAL')
    op.drop_table('group', schema='STG_SOCIAL')
    op.drop_table('create_group_request', schema='STG_SOCIAL')
    op.drop_table('dynamic_option', schema='STG_AUTH')
    op.drop_table('achievement_receiver', schema='STG_ACHIEVEMENT')
    op.drop_table('achievement', schema='STG_ACHIEVEMENT')
    op.delete_group(
        "test_dwh_stg_achievement_all" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_achievement_all"
    )
    op.delete_group(
        "test_dwh_stg_achievement_write"
        if os.getenv("ENVIRONMENT") != "production"
        else "prod_dwh_stg_achievement_write"
    )
    op.delete_group(
        "test_dwh_stg_achievement_read" if os.getenv("ENVIRONMENT") != "production" else "prod_dwh_stg_achievement_read"
    )
    op.drop_table_schema("STG_ACHIEVEMENT")
    op.create_table(
        'vk_groups',
        sa.Column(
            'id',
            sa.INTEGER(),
            server_default=sa.text('nextval(\'"STG_SOCIAL".vk_groups_id_seq\'::regclass)'),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('confirmation_token', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('secret_key', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('create_ts', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column('update_ts', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('id', name='vk_groups_pkey'),
        schema='STG_SOCIAL',
    )
    op.create_table(
        'raw_html_old',
        sa.Column('url', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
        sa.Column('raw_html', sa.TEXT(), autoincrement=False, nullable=True),
        schema='STG_TIMETABLE',
    )
    op.grant_on_table(
        (
            "test_dwh_stg_timetable_all"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_test_dwh_stg_timetable_all"
        ),
        [
            'INSERT',
            'SELECT',
            'UPDATE',
            'DELETE',
            'TRUNCATE',
            'REFERENCES',
            'TRIGGER',
        ],
        '"STG_TIMETABLE".raw_html_old',
    )
    op.grant_on_table(
        (
            "test_dwh_stg_timetable_write"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_test_dwh_stg_timetable_write"
        ),
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"STG_TIMETABLE".raw_html_old',
    )
    op.grant_on_table(
        (
            "test_dwh_stg_timetable_read"
            if os.getenv("ENVIRONMENT") != "production"
            else "prod_test_dwh_stg_timetable_read"
        ),
        ['SELECT'],
        '"STG_TIMETABLE".raw_html_old',
    )
    op.grant_on_table(
        "test_dwh_stg_social_all" if os.getenv("ENVIRONMENT") != "production" else "prod_test_dwh_stg_social_all",
        [
            'INSERT',
            'SELECT',
            'UPDATE',
            'DELETE',
            'TRUNCATE',
            'REFERENCES',
            'TRIGGER',
        ],
        '"STG_SOCIAL".vk_groups',
    )
    op.grant_on_table(
        ("test_dwh_stg_social_write" if os.getenv("ENVIRONMENT") != "production" else "prod_test_dwh_stg_social_write"),
        ['SELECT', 'UPDATE', 'DELETE', 'TRUNCATE', 'INSERT'],
        '"STG_SOCIAL".vk_groups',
    )
    op.grant_on_table(
        ("test_dwh_stg_social_read" if os.getenv("ENVIRONMENT") != "production" else "prod_test_dwh_stg_social_read"),
        ['SELECT'],
        '"STG_SOCIAL".vk_groups',
    )
    op.alter_column('raw_html', 'raw_html', existing_type=sa.TEXT(), nullable=True, schema='STG_TIMETABLE')
    op.alter_column('raw_html', 'url', existing_type=sa.VARCHAR(length=256), nullable=True, schema='STG_TIMETABLE')
    op.drop_column('webhook_storage', 'event_ts', schema='STG_SOCIAL')
    op.drop_column('scope', 'is_required', schema='STG_SERVICES')
    op.drop_column('scope', 'button_id', schema='STG_SERVICES')
    # ### end Alembic commands ###
